<div class="jumbotron">
	<h1>Welcome to the NEW[est] farstrider.eu!</h1>
	
	<p>After another prolonged period of inactivity, I've started actively developing this site again (^_^;)  
    However, aside from the look -- for which I'm currently experimenting with <a href="http://getbootstrap.com">Bootstrap</a> 
    -- only the temple tracker is getting a lot of work right now.</p>
        	
	<p>This time around, I decided to make my source code public on <a href="https://github.com/farstrider/farstrider.eu">GitHub</a>.
    I did this for two main reasons:</p>
       		
	<ol>
		<li>So that I can benefit from the wisdom and advice of the numerous experts out there who are far more knowledgeable than me.</li>
		<li>So that some of my work is available to show off to potential employers.</li>
	</ol>
    		
	<p>As I'm now trying to pick up my development career again after three years of teaching English with the JET Program, 
	I'm going to do my best to make this iteration a sustained effort.  So keep an eye out for new content and features on a regular 
	basis!</p>
</div>